name: Template - Collect Results

on:
  workflow_call:
    inputs:
      result-prefix:
        required: false
        type: string
        default: ''

permissions:
  contents: read

jobs:
  collect-results:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          token: ${{ secrets.REPO_PAT }}
          fetch-depth: 0

      - name: Download JSON artifacts
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          path: results/
          pattern: ${{ inputs.result-prefix && format('{0}_*', inputs.result-prefix) || '*' }}

      - name: Print summary
        run: |
          pip install tabulate
          python3 utils/summarize.py results/ >> $GITHUB_STEP_SUMMARY

      - name: Aggregate results
        run: python3 utils/collect_results.py results/ ${{ inputs.result-prefix || 'all' }}

      - name: Upload aggregated results
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: results_${{ inputs.result-prefix || 'all' }}
          path: agg_${{ inputs.result-prefix || 'all' }}.json
